from .usuario import Usuario
from .rol import Rol
from .universidad import Universidad
from .carrera import Carrera
from .carrera_universidad import carrera_universidad
from .curso import Curso
from .clase import Clase
from .facultad import Facultad
from .inscripcion import Inscripcion
from .inscripcion_universidad import InscripcionUniversidad
from .inscripciones_plataforma import InscripcionPlataforma
from .regimen import Regimen
from .comentario import Comentario